FitCheckApp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),                 # Admin page
    path('', include('UserProfile.urls')),
    path('', include('FoodAnalysis.urls')),  # Add this line
    path('fitnessPlanning/', include('FitnessPlanning.urls', namespace="FitnessPlanning")),
    path('nutritionguidance/', include('NutritionGuidance.urls', namespace="NutritionGuidance")),
    path('wellness/', include('wellnesstrack.urls', namespace='wellnesstrack')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

NutritionGuidance/urls.py
from django.urls import path
from .views import ng_homeview, ht_create, NG_MPListView, NG_NextMeal, NG_Recipe, HT_Update, HT_Delete

urlpatterns = [
    path('home/', ng_homeview, name='ng_index'),
    path('meal_plan/', NG_MPListView.as_view(), name='ng_planlist'),
    path('nextmeal/', NG_NextMeal.as_view(), name='ng_nextmeal'),
    path('recipe/<meal_id>', NG_Recipe.as_view(), name='ng_recipe'),
    path('hydrotrack/', ht_create, name='ht_create'),
    path('hydrotrack/settings', HT_Update.as_view(), name='ht_update'),
    path('hydrotrack/disable', HT_Delete.as_view(), name='ht_delete')
]

app_name="NutritionGuidance"

urls.py
from django.urls import path
from . import views

app_name = 'wellnesstracker'  # <-- This is the key line

urlpatterns = [
    path('bmi/', views.bmi_form, name='bmi_form'),
    path('mood/', views.mood_form, name='mood_form'),
    path('sleep/', views.sleep_form, name='sleep_form'),
    path('past-analyses/', views.past_analyses, name='past_analyses'),
]

NutritionGuidance/models.py
from django.db import models
from django.urls import reverse

# Create your models here.
class Allergen(models.Model):
    allergen_id = models.AutoField(primary_key=True)
    allergen_name = models.CharField(max_length=256, null=False)
    
    def __str__(self):
        return self.allergen_name
    
class Ingredient(models.Model):
    ingredient_id = models.AutoField(primary_key=True)
    ingredient_name = models.CharField(max_length=256, null=False)  
    
    def __str__(self):
        return self.ingredient_name 

class Recipe(models.Model):
    recipe_id = models.AutoField(primary_key=True)
    recipe_instructions = models.TextField()

class Recipe_Ingredients(models.Model):
    recipe_id = models.ForeignKey('Recipe', related_name='ingredient', on_delete=models.CASCADE)
    ingredient_id = models.ForeignKey('Ingredient', related_name='recipe', on_delete=models.CASCADE)
    quantity = models.CharField(max_length=20, null=False)
    
    def __str__(self):
        return f'{self.ingredient_id} - {self.quantity}'
    
    class Meta:
        unique_together = ['recipe_id', 'ingredient_id'] # Ensures a recipe may only use an ingredient once (not quantity-wise) 
    
class Meal(models.Model):
    meal_id = models.AutoField(primary_key=True)
    meal_name = models.CharField(max_length=256, null=False)   
    recipe_id = models.ForeignKey('Recipe', related_name="recipe", on_delete=models.CASCADE)
    allergen_id = models.ForeignKey('Allergen', related_name="allergen", on_delete=models.CASCADE, null=True, blank=True)
    calories = models.IntegerField(default=1)
    
    def __str__(self):
        return self.meal_name
    
class Meal_Plan(models.Model):
    MEAL_TYPE = (
        ("breakfast", "Breakfast"),
        ("lunch", "Lunch"),
        ("dinner", "Dinner")
    )
    DAY = (
        ("sun", "Sunday"),
        ("mon", "Monday"),
        ("tue", "Tuesday"),
        ("wed", "Wednesday"),
        ("thu", "Thursday"),
        ("fri", "Friday"),
        ("sat", "Saturday"),
    )
    user_id = models.ForeignKey('UserProfile.User', related_name='meal_plan', on_delete=models.CASCADE)
    meal_id = models.ForeignKey('Meal', related_name='meal_plan', on_delete=models.CASCADE)
    meal_type = models.CharField(choices=MEAL_TYPE, max_length=32)
    day = models.CharField(choices=DAY) 
    
    def __str__(self):
        return f'{self.user_id} - {self.meal_id.meal_name} ({self.day} {self.meal_type})'
    
class Hydration_Tracker(models.Model):
    user_id = models.ForeignKey('UserProfile.User', related_name='hydration_tracker', on_delete=models.CASCADE)
    container_size = models.FloatField()
    water_goal = models.FloatField()
    active_start = models.TimeField(default="0:00")
    active_end = models.TimeField(default="23:59")
    

NutritionGuidance/forms.py
from django import forms

from .models import Meal, Meal_Plan, Hydration_Tracker

class HydrationTrackerForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args,**kwargs)
        self.label_suffix = ""
    class Meta:
        model = Hydration_Tracker
        fields = ['container_size', 'water_goal', 'active_start', 'active_end']
        widgets = {
            'container_size': forms.NumberInput(attrs={'placeholder': 'Input container size (mL) '}),
            'water_goal': forms.NumberInput(attrs={'placeholder': 'Input daily water goal (mL) '}),
            'active_start': forms.TimeInput(attrs={'placeholder': 'Input start of day (ex. 0:00) '}),
            'active_end': forms.TimeInput(attrs={'placeholder': 'Input end of day (ex. 23:59) '})
        }

NutritionGuidance/views.py
from django.views import View
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from UserProfile.models import User
from .forms import HydrationTrackerForm
from .models import Meal, Meal_Plan, Hydration_Tracker
from FitnessPlanning.models import CalorieDeficitPlanner


@login_required(login_url='/')
def ng_homeview(request):
    message = ""
    if request.method == 'POST':
        user = User.objects.get(user_id=request.user.user_id)
        allergies = user.allergy_name
        queried_meals = Meal.objects.exclude(allergen_id__allergen_name__contains=allergies).filter(calories__lte=2100/3).order_by('?')[:21]
            # assign them to different meal types (breakfast, lunch, dinner)
        meal_type = ["breakfast", "lunch", "dinner"]
            # assign them to different days of the week
        days = ["sun", "mon", "tue", "wed", "thu", "fri", "sat"]
        
        for i in range(len(days)):
            for j in range(len(meal_type)):
                mealplan = Meal_Plan()
                mealplan.user_id = user
                mealplan.meal_id = queried_meals[i*3 + j]
                mealplan.meal_type = meal_type[j]
                mealplan.day = days[i]
                mealplan.save()

        return redirect('NutritionGuidance:ng_index')
            
    else:
        user = User.objects.get(user_id=request.user.user_id)
        current_meal = Meal_Plan.objects.filter(user_id=user).first()
        ht = Hydration_Tracker.objects.filter(user_id=user).first()
    return render(request, 'index.html', {'current_meal': current_meal, 'ht': ht, 'message': message})

@login_required(login_url="/")
def ht_create(request):
    if request.method == 'POST':
        htform = HydrationTrackerForm(request.POST, prefix='hydrotracker')
        if htform.is_valid():
            ht = Hydration_Tracker()
            ht.user_id = User.objects.get(user_id=request.user.user_id)
            ht.container_size = htform.cleaned_data.get('container_size')
            ht.water_goal = htform.cleaned_data.get('water_goal')
            ht.active_start = htform.cleaned_data.get('active_start')
            ht.active_end = htform.cleaned_data.get('active_end')
            ht.save()
            
            return redirect('NutritionGuidance:ng_index')
    else:
        htform = HydrationTrackerForm(prefix='hydrotracker')
    return render(request, 'ht_form.html', {'form': htform})

class NG_MPListView(LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        meals = Meal_Plan.objects.filter(user_id=self.request.user)
        days = {
            "sun": "Sunday",
            "mon": "Monday",
            "tue": "Tuesday",
            "wed": "Wednesday",
            "thu": "Thursday",
            "fri": "Friday",
            "sat": "Saturday",
        }
        
        return render(request, 'planlist.html', {'meals': meals, "days": days})
    
class NG_NextMeal(View):
    def post(self, request, *args, **kwargs):
        meal = Meal_Plan.objects.filter(user_id=self.request.user).first()
        meal.delete()
        return redirect('NutritionGuidance:ng_index')

class NG_Recipe(View):
    def get(self, request, meal_id, *args, **kwargs):
        meal = Meal.objects.get(meal_name=meal_id)
        return render(request, 'recipe.html', {'meal': meal})

class HT_Update(View):
    def get(self, request):
        tracker = Hydration_Tracker.objects.get(user_id=self.request.user)
        htform = HydrationTrackerForm(instance=tracker)
        return render(request, 'ht_form.html', {'form': htform})
    
    def post(self, request):
        tracker = Hydration_Tracker.objects.get(user_id=self.request.user)
        htform = HydrationTrackerForm(request.POST, instance=tracker)
        if htform.is_valid():
            htform.save()
            return redirect('NutritionGuidance:ng_index')
        return render(request, 'ht_form.html', {'form': htform})
    
class HT_Delete(View):
    def post(self, request, *args, **kwargs):
        tracker = Hydration_Tracker.objects.get(user_id=self.request.user)
        tracker.delete()
        return redirect('NutritionGuidance:ng_index')
            
        

NutritionGuidance/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <script src="https://kit.fontawesome.com/4a1b605065.js" crossorigin="anonymous"></script>
  <title>FitCheck Dashboard</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <style>
    * {
      box-sizing: border-box;
    }

    body {
      margin: 0;
      font-family: Arial, sans-serif;
      background: #f4f4f4;
      height: 100vh;
      display: flex;
    }

    .button {
      background-color: black;
      color:white;
      border: 1px, solid, black;
      padding: 15px 30px;
      border-radius: 20px;
    }

    .button:hover {
      color: black;
      background-color: white;
    }
    .button:active {
      color: black;
      background-color: white;
      border-color: white;
    }
    
    .sidebar {
      width: 220px;
      background-color: #AED9E0;
      color: black;
      padding: 20px;
      flex-shrink: 0;
      display: flex;
      flex-direction: column;
      border-right: 1px solid black;
    }

    .sidebar h2 {
      margin-top: 0;
      font-size: 1.4rem;
    }

    .sidebar a {
      display: block;
      color: #5E6472;
      text-decoration: none;
      margin: 10px 0;
      padding: 15px;
      border-radius: 5px;
    }

    .sidebar a:hover {
      background-color: #B8F2E6;
    }

    .main {
      flex: 1;
      display: flex;
      flex-direction: column;
      height: 100vh;
    }

    .topbar {
      background-color: #AED9E0;
      color: black;
      padding: 15px 30px;
      font-size: 20px;
      font-weight: bold;
      box-shadow: 0 2px 5px rgba(0,0,0,0.1);
      text-align: end;
      border-bottom: 1px solid black;
    }

    .content {
      flex: 1;
      padding: 30px;
      background: linear-gradient(#AED9E0, #FAF3DD, #B5DCE1);;
      overflow-y: auto;
    }

    input[type=text] {
        width: 20%;
        padding: 12px 10px;
        margin: 8px 0;
        box-sizing: border-box;
    }

    input[type=number] {
        width: 25%;
        padding: 12px 10px;
        margin: 8px 0;
        box-sizing: border-box;
    }

    footer {
      text-align: center;
      padding: 5px;
      color: #888;
      background: #f0f0f0;
    }
  </style>
</head>
<body>

  <!-- Sidebar -->
  <div class="sidebar">
    <h2>FitCheck</h2>
    <a href="#"><i class="fas fa-compass"></i> Dashboard</a>
    <a href="#"> <i class="fas fa-user"></i>  Profile </a>
    <a href="#"> <i class="fas fa-puzzle-piece"></i>  Food Analysis </a>
    <a href="#"><i class="fas fa-spoon"></i> FitnessPlanning</a>
    <a href="{% url 'NutritionGuidance:ng_index' %}"><i class="fas fa-book"></i> Nutrition Guidance</a>
    <a href="#"><i class="fas fa-heartbeat"></i> Wellness Tracker</a>
    <a href="#">Logout</a>
  </div>

  <!-- Main Area (Topbar + Content) -->
  <div class="main">
    <div class="topbar">
      Welcome, User!
      <i class="fas fa-user-circle"></i>
    </div>
    <div class="content">
      {% block content %}
      {% endblock %}
    </div>
    <!-- <footer>
        FitCheck 
    </footer> -->
  </div>

</body>
</html>

NutritionGuidance/templates/ht_form.html
{% extends 'base.html' %}

{% block content %}
    <style>
        input {
            width: 200px;
            padding: 10px;
            margin: 8px 0;
            margin-left: 0px;
            display: block;
        }
        label {
            display: block;
            text-align: left;
            margin-left: 0px;
        }
    
        h1 {
            text-align: center;
        }
        .form {
            background-color: rgba(255, 255, 255, 0.9);
            padding: 20px;
            border-radius: 15px;
            box-shadow: 2px 2px 10px rgba(0, 0, 0, 0.2);
            margin: 10px;
            width: 50%;
            display: inline-block;
            text-align:center;
        }
        
    </style>
        <div class="form">
            <h1> Set a hydration tracker </h1>
            <form method="post" class="form">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="button">Set tracker</button>
            </form>
        </div>

{% endblock %}

NutritionGuidance/templates/index.html
{% extends 'base.html' %}
{% block content %}
<style>
    * {
      box-sizing: border-box;
    }

    body {
      margin: 0;
      font-family: Arial, sans-serif;
      background: #f4f4f4;
      height: 100vh;
      display: flex;
    }

    button {
        margin-top: 0px;
    }

    .button {
      background-color: black;
      color:white;
      border: 1px, solid, black;
      padding: 15px 30px;
      border-radius: 20px;
    }

    .button:hover {
      color: black;
      background-color: white;
    }
    .button:active {
      color: black;
      background-color: white;
      border-color: white;
    }

    .sidebar {
      width: 220px;
      background-color: #AED9E0;
      color: black;
      padding: 20px;
      flex-shrink: 0;
      display: flex;
      flex-direction: column;
      border-right: 1px solid black;
    }

    .sidebar h2 {
      margin-top: 0;
      font-size: 1.4rem;
    }

    .sidebar a {
      display: block;
      color: #5E6472;
      text-decoration: none;
      margin: 10px 0;
      padding: 15px;
      border-radius: 5px;
    }

    .sidebar a:hover {
      background-color: #B8F2E6;
    }

    .sidebar a.active {
      background-color: #4CAF50;
      color: white;
    }

    .main {
      flex: 1;
      display: flex;
      flex-direction: column;
      height: 100vh;
    }

    .topbar {
      background-color: #AED9E0;
      color: black;
      padding: 15px 30px;
      font-size: 20px;
      font-weight: bold;
      box-shadow: 0 2px 5px rgba(0,0,0,0.1);
      text-align: end;
      border-bottom: 1px solid black;
    }

    .content {
      flex: 1;
      padding: 30px;
      background: linear-gradient(#AED9E0, #FAF3DD, #B5DCE1);;
      overflow-y: auto;
    }

    footer {
      text-align: center;
      padding: 5px;
      color: #888;
      background: #f0f0f0;
    }
    form {
        float: left;
    }
</style>
    <!-- Meal Plan Generation -->
    <div class="meal_plan" style="float:left; margin-top: -30px; margin-left: -30px; padding-left: 22px; width: 648px; height: 260px; flex-shrink: 0; border: 1.5px solid #000000; border-left-style: hidden; border-top-style: hidden">
    {% if current_meal %}
        <h4 style="width: 617px; height: 20px; margin-bottom: 15px; font-size: 20px"> Next Meal: </h4>
        <h2 style="font-size: 32px; margin-top: 0px; margin-bottom: 0px"> {{ current_meal.get_meal_type_display }}: {{ current_meal.meal_id.meal_name }} </h2>

        <br />
        <form action="{% url 'NutritionGuidance:ng_nextmeal' %}" method="post">
            {% csrf_token %}
            <button type="submit" class="button" style="float: left; margin-left: 30px; margin-top: 47px; margin-right: 25px">Proceed to Next Meal</button>
        </form>
        <br />
        <form action="{% url 'NutritionGuidance:ng_recipe' current_meal.meal_id %}">
            <button type="submit" class="button" style="float:left; margin-right: 25px; margin-top: 28px; padding-bottom: 15px">View Recipe</button>
        </form>
        <br />
        <form action="{% url 'NutritionGuidance:ng_planlist' %}">
          <button type="submit" class="button" style="float: left; margin-top: 10px">View Meal Plan</button>
        </form>
    {% else %}
      <p style="width: 617px; height: 20px; margin-bottom: 15px; font-size: 20px"> No meal plan found! Generate one now: </p>
      <form method="post">
          {% csrf_token %}
          <button type="submit" class="button">Generate Meal Plan</button>
      </form>
      <br />
    {% endif %}
    </div>
    <!-- Hydration tracker -->
    <div style="float: left; margin-top: -30px; padding-left: 22px; width: 580px; height: 260px; flex-shrink: 0; border: 1.5px solid #000000; border-left-style: hidden; border-top-style: hidden;">
    {% if ht %}
    {{ ht.water_goal|json_script:"water_goal" }}
    {{ ht.container_size|json_script:"cont_size" }}
    {{ ht.active_end|json_script:"active_end" }}
    {{ ht.active_start|json_script:"active_start" }}
    <h4 style="width: 617px; height: 20px; margin-bottom: 15px; font-size: 20px"> Next water notification at: </h4>
    <h2 id="next" style="font-size: 64px; margin-top: 0px; margin-bottom: 0px"></h2>
    <br />
    <form action="{% url 'NutritionGuidance:ht_update' %}">
        <button type="submit" class="button" style="float: left; margin-top: 10px; margin-left: 25px; margin-right: 35px">Configure Hydration Tracker</button>
    </form>
    <form action="{% url 'NutritionGuidance:ht_delete' %}" method="post">
        {% csrf_token %}
        <button type="submit" class="button" style="float: left; margin-top: 10px">Disable Hydration Tracker</button>
    </form>
    <script>
        // variables calculations
        // times to drink = water goal / container size (ceiling division)
        // active hours = active end - active start
        // intervals = active hours / times to drink
        
        const water_goal = JSON.parse(document.getElementById('water_goal').textContent);
        const cont_size = JSON.parse(document.getElementById('cont_size').textContent);
        const active_end = JSON.parse(document.getElementById('active_end').textContent);
        const active_end_hours = parseInt(active_end);
        const active_end_minutes = active_end.substring(3,5);
        const active_start = JSON.parse(document.getElementById('active_start').textContent);
        const active_start_hours = parseInt(active_start);
        const active_start_minutes = active_start.substring(3,5);

        const times_to_drink = Math.ceil(water_goal/cont_size);
        const active_hours = active_end_hours - active_start_hours;
        const active_minutes = parseInt(active_end_minutes) - parseInt(active_start_minutes);
        const intervals = (active_hours + (active_minutes / 60))/times_to_drink;
        let next_hours = 0;
        let next_minutes = 0;


        // function to get next notification at any time
        // nowfromthen = current time - active start
        // progress = nowfromthen / intervals
        // nextnotif = active start + intervals*(progress) + intervals
        function nextNotif() {
            
            const current = new Date();
            const current_hours = current.getHours();
            const current_minutes = current.getMinutes();
            const nowfromthen_hours = current_hours - active_start_hours;
            const nowfromthen_minutes = current_minutes - parseInt(active_start_minutes);
            const progress = Math.floor((nowfromthen_hours + (nowfromthen_minutes / 60))/intervals);

            next_hours = Math.floor(active_start_hours + intervals*(progress + 1));
            next_minutes = Math.floor(parseInt(active_start_minutes) + ((intervals%1)*60)*(progress + 1));

            if (next_minutes >= 60){
                next_hours += Math.floor(next_minutes/60);
                next_minutes = next_minutes % 60;
            }
            next_hours = next_hours.toLocaleString('en-US', {minimumIntegerDigits: 2, useGrouping: false});
            next_minutes = next_minutes.toLocaleString('en-US', {minimumIntegerDigits: 2, useGrouping: false});
            if ((next_hours > active_end_hours || (next_hours == active_end_hours && next_minutes > active_end_minutes)
                    || next_hours < active_start_hours)){
                document.getElementById('next').innerHTML = active_start_hours.toLocaleString('en-US', {minimumIntegerDigits: 2, useGrouping: false}) 
                                                    + ":" + active_start_minutes.toLocaleString('en-US', {minimumIntegerDigits: 2, useGrouping: false});
            }
            else {
                document.getElementById('next').innerHTML = next_hours + ":" + next_minutes;
            }
            
        }

        // function to check notifications
        // if current time >= current notification time
        // javascript alert
        function checkNotif() {
            const current = new Date();
            const current_hours = current.getHours();
            const current_minutes = current.getMinutes();

            if (current_hours == next_hours && current_minutes == next_minutes){
                alert("You should drink water NOW!");
            }
        }

        // poll check function every minute
        setInterval(checkNotif, 10000);

        // get next notification on page load
        nextNotif();
        

    </script>
    {% else %}
    <p style="width: 617px; height: 20px; margin-bottom: 15px; font-size: 20px">No tracker found! Create one now: </p>
    <form action="{% url 'NutritionGuidance:ht_create' %}">
        <button type="submit" class="button">Set Hydration Tracker</button>
      </form>
    {% endif %}
    </div>
{% endblock %}

NutritionGuidance/templates/planlist.html
{% extends 'base.html' %}
{% block content %}
<style>
    .bg {
        background-color: rgba(255, 255, 255, 0.9);
        padding: 20px;
        padding-left: 90px;
        border-radius: 15px;
        box-shadow: 2px 2px 10px rgba(0, 0, 0, 0.2);
        margin: 10px;
        width: 50%;
        display: inline-flex;
        text-align: center;
    }
    h2 {
        font-size: 64px;
        margin-bottom: 10px;
        margin-top: 20px;
    }
    ul {
        list-style-type: none;
    }
    li {
        padding: 5px 0;
        font-size: 20px;
    }
</style>
    <div class="bg">
        <ul>
        {% for key, day in days.items %}
            <h2> {{ day }}</h2>
            {% for meal in meals %}
                {% if meal.day == key %}
                <li>
                    {{ meal.get_meal_type_display }}: {{ meal.meal_id.meal_name }}
                    <form action="{% url 'NutritionGuidance:ng_recipe' meal.meal_id %}">
                        <button type="submit" class="button" style="margin: 10px 0">View Recipe</button>
                    </form>
                </li>
                {% endif %}
            {% endfor %}
        {% endfor %}
        </ul>
    </div>
{% endblock %}

NutritionGuidance/templates/recipe.html
{% extends 'base.html' %}
{% block content %}
<style>
    .bg {
        background-color: rgba(255, 255, 255, 0.9);
        padding: 20px;
        border-radius: 15px;
        box-shadow: 2px 2px 10px rgba(0, 0, 0, 0.2);
        margin: 10px;
        width: 50%;
        display: inline-block;
        text-align: left;
    }
    h2 {
        font-size: 48px;
        margin-bottom: 10px;
        margin-top: 20px;
    }
    ul {
        list-style-type: none;
    }
    li {
        padding: 5px 0;
        font-size: 20px;
    }
</style>
<div class="bg">
    <h2 style="font-size: 64px; text-align: center;"> {{ meal.meal_name }}</h2>
    <ul>
        <h2> Ingredients: </h2>
        {% for ingredient in meal.recipe_id.ingredient.all %}
            <li> {{ ingredient }} </li>
        {% endfor %}
        <br />
        <h2> Instructions </h2>
        <p> {{ meal.recipe_id.recipe_instructions }} </p>
    </ul>
</div>
{% endblock %}